
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV MONGODB_URI=MONGODB_URL
ENV MONGODB_DBNAME=MONGODB_DBNAME
ENV PORT=PORT
ENV JWT_SECRET=JWT_SECRET
ENV GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID
ENV JWT_REFRESH_SECRET=JWT_REFRESH_SECRET
ENV BASE_URL=http://localhost:8080
ENV CLOUDINARY_NAME=CLOUDINARY_NAME
ENV CLOUDINARY_API_KEY=CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET

EXPOSE 8080

CMD [ "node", "index.js" ]